server.port=8819
spring.application.name=payment-service

# ==========================================
# CẤU HÌNH DATABASE (AIVEN POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/defaultdb
spring.datasource.username=your_db_username
spring.datasource.password=your_db_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# VNPAY
vnpay.tmn-code=your_vnpay_tmn_code
vnpay.hash-secret=your_vnpay_hash_secret
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/payments/vnpay/return
vnpay.frontend-success-url=http://localhost:3000/checkout
vnpay.frontend-fail-url=http://localhost:3000/checkout
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
