# ==========================================
# CẤU HÌNH SERVER & EUREKA
# ==========================================
server.port=8816
spring.application.name=setting-service

# ==========================================
# CẤU HÌNH DATABASE (AIVEN POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/defaultdb
spring.datasource.username=your_db_username
spring.datasource.password=your_db_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# ==========================================
# CẤU HÌNH DATABASE (MySQL)
# ==========================================

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# ERROR MESSAGES
# ==========================================
error.404.schema.details=Setting not found
error.406.schema.details=This request is not acceptable. Supported MIME types are application/json
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
